version: '3.8'

services:
  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    ports:
      - 3000:3000

  client:
    container_name: client
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    depends_on:
      - api
    ports:
      - 8080:8080
  
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=2223 
      - POSTGRES_USER=postgres 
      - POSTGRES_DB=test3
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: api-db