export const QUERY_KEYS = {
  ORDERS: "ORDERS",
  USERS: "USERS",
  ORDER: "ORDER",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  REGISTRATION: "REGISTRATION",
  PRODUCTS: "PRODUCTS",
  PRODUCT: "PRODUCT",
};
